### ISSUE TITLE
/home/$USER/Desktop sometimes not exist

### ISSUE THREAD

**Issue by xuxincheng** [JBakamovic/yavide#22]
echo "$passwd" | sudo -S cp yavide.desktop /home/$USER/Desktop

some directory maybe not exist
for example , ,my /home/root/Desktop does not exist
then yavide_desktop will be cp to /home/root, and rename as Desktop
then fail.

maybe you can mkdir -p $dir before using.

**Comment by JBakamovic** [comment]
Okay, I am aware there is plenty of space to make the installation script more bullet-proof. However, I wouldn't expect the script to fail at this step. It turns out that it can indeed fail for localized machines, like the one you are supposedly running. There seems to be a way to circumvent the localization issues by utilizing `xdg-user-dirs` tool. I will apply this technique shortly so let me know if it fixed it for you.
