### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by SameerAsal** [JBakamovic/yavide#36]
Hi, 

This might be a silly question, after doing the installation no changes were done to the .vimrc file. How di we expect the plugin to get loaded at all?

**Comment by JBakamovic** [comment]
It's not a silly question :) This was one of the goals of this project. `Yavide` installation will not mess-up with your local `(g)vim` configuration but it will instead act as a standalone & self-contained `(g)vim` instance. It achieves that by modifying the runtime path of the `(g)vim` so that it points to the `Yavide` installation directory.

All the relevant configuration files and code is which is executed by `Yavide` is exactly in its installation directory.

**Comment by SameerAsal** [comment]
I see. That makes sense!
