### ISSUE TITLE
Very strange behavior with autocomplete

### ISSUE THREAD

**Issue by ks-zealot** [JBakamovic/yavide#90]
I have project with Vulkan SDK support and some other libs (GLFW, for example). And I could not call clang autocomplete in main.cpp file.
But, I could use autocomplete from another libs.
And, if i copy this file, I could call autocomplete from this copy.
Could you tell me what I do wrong?
.clang_autocomplete
`-DDEBUG
-std=c++17
-I/usr/include/c++/6.3.0/
-I/usr/include/GL
-I${HOME}/VulkanSDK/1.0.61.1/x86_64/include`

Project structure
![image](https://user-images.githubusercontent.com/7972618/40848471-023818b8-65c8-11e8-9c59-8605df8c555f.png)
main.cpp
![image](https://user-images.githubusercontent.com/7972618/40848497-1cca1dc0-65c8-11e8-8810-9d50d1aeb400.png)
The text below - User autocompletion (Tempalte not found)
main.cpp, autocompletion from GLFW
![image](https://user-images.githubusercontent.com/7972618/40848607-674269f2-65c8-11e8-84e8-297cf4cb6c97.png)

main1.cpp
![image](https://user-images.githubusercontent.com/7972618/40848556-4342e036-65c8-11e8-91d8-492347a1f163.png)

**Comment by JBakamovic** [comment]
I am not sure if I understood you correctly but you're trying to say that autocompletion is not working for Vulkan API from `main.cpp` but from `main1.cpp` it does?

Can you try removing `${HOME}` from `-I${HOME}/VulkanSDK/1.0.61.1/x86_64/include` line and replace it with the full path? I am not sure if environment variables are handled correctly (expanded).

**Comment by ks-zealot** [comment]
I have not environment variable in my config. I just placehold my homedir when copypast because reason.
Anyway, I already solved this problem just copying whole folder and reimport project.
Another issue, could you tell me how could I include YCM in your IDE? Or at least how could i automatically fix error, if clang know how to fix it (FixIt function in YCM).

**Comment by JBakamovic** [comment]
> Another issue, could you tell me how could I include YCM in your IDE?

Just download the plugin into `<yavide_install_dir>/core/external` directory. If you do that, then it would be wise to disable `clang-complete` plugin otherwise you will get weird behavior.

> Or at least how could i automatically fix error, if clang know how to fix it (FixIt function in YCM).

Not available here. But for [such and more features](https://github.com/JBakamovic/cxxd/blob/master/README.md#features) please have a look into my other project, [cxxd-vim](https://github.com/JBakamovic/cxxd-vim), which is no more than a Vim plugin but built on top of the language server, [cxxd](https://github.com/JBakamovic/cxxd), which I have also developed separately. Currently, I am finishing up the implementation of auto-completion service, which is one of the last major features I wanted to bring in. It's work-in-progress but already in a good shape so I think it could be merged to master quite soon.

**Comment by ks-zealot** [comment]
>  If you do that, then it would be wise to disable clang-complete plugin otherwise you will get weird behavior.
How could i do this?
>cxxd
Looks very interesting, I will try this when you finish auto-completion.

**Comment by JBakamovic** [comment]
Just like you would do for any other Vim plugin. Rename it to `<name_of_the_plugin>~`

**Comment by ks-zealot** [comment]
Sorry, I dont get it. How could I disable plugin by renaming?
