### ISSUE TITLE
Errors on startup and while typing

### ISSUE THREAD

**Issue by IMMZ** [JBakamovic/yavide#94]
Info:
===========================
OS: Debian Jessie 8
Vim python support: yes
Vim python3 support: no
No errors during yavide installation.

Problem:
===========================
I get some errors you can see on the screenshots while typing and some errors on startup. What's the problem and how can I fix them?

This is when I open the IDE
![ide_open](https://user-images.githubusercontent.com/1856709/47609308-b2f78f80-da44-11e8-9b6c-bb2e79af375b.png)

This is everytime I try to code - after every key press.
![cxxd](https://user-images.githubusercontent.com/1856709/47609307-b25ef900-da44-11e8-962b-0f067f0d2b87.png)

**Comment by JBakamovic** [comment]
Can you translate error message from startup to English please?

**Comment by IMMZ** [comment]
Sure.
1) MessageBox:
Error occured during processing /opt/yavide/core/.editor.vimrc"
line 82:
E121: Undefined variable v:true
E116: Invalid parameters for function Y_Buffer_Auto....

2) Errors in editor
Error occured during processing function cxxd#...

E117: Unknown function: getbufinfo
Press ENTER or enter command to continue

Error occured during processing function cxxd#...

E15: Invalid expression: getbufinfo...changedtick
Press ENTER or enter command to continue

The rest of errors tell about invalid expression or undefined variable v:true/false

When I press Enter many times the errors dissapear. But when I press anything they appears again.

**Comment by JBakamovic** [comment]
`v:true/v:false` and `getbufinfo()` are built-ins from Vim itself and it seems that version of Vim you're running (some older one?) does not have support for these. You will need to update your Vim instance to a more recent version.

**Comment by JBakamovic** [comment]
Moreover, `yavide` development is basically stopped because its core functionality has been refactored into two separate repositories: [cxxd](https://github.com/JBakamovic/cxxd) & [cxxd-vim](https://github.com/JBakamovic/cxxd-vim). `Yavide` still consumes the very same functionality by having those repos integrated as submodules but my suggestion is to not bother too much with `Yavide` anymore but simply use vanilla Vim plugin that is hosted in [cxxd-vim](https://github.com/JBakamovic/cxxd-vim) repo.
